# Site settings
title: Pistou.io
header-img: img/header.jpg
email: skowron.pierre@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://pistou.io"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  toc_levels: 1..2

permalink: /:year-:month-:day-:title
paginate: 5
paginate_path: "/blog/:num/"

gems: [jekyll-paginate, jekyll-feed, jemoji]

# Assets
sass:
    sass_dir: _scss
    style: compressed

# Social medias
media_twitter: pistoudev
media_instagram: pistoudev
media_github: pistou
media_linkedin: pierre-skowron-b26546106
media_stackoverflow: 2099704/pistou
media_facebook : pistoudev
